---
title: " "
author: ""
date: ""
output: html_document
---

Hello.

You are currently enrolled in my section of **IDS111 -- Northland Highways**. Below are several announcements regarding this course.

* On Thursday, we will meet in room 247 of the Center for Science and Environment (the "Science Building"). Note that your schedule from the MyNorthland may say that we meet in the Alvord Theatre, but that is incorrect.
* A website with all course materials is at http://derekogle.com/NCHighways/. Please note that I host the class website on my personal webpage and not on the Northland portal. Thus, please use the address in the first sentence, rather than going through MyNorthland.
* You will need to purchase the *College Rules* textbook. This is available from Amazon for approximately $9 ([see here](https://www.amazon.com/College-Rules-4th-Survive-Succeed/dp/1607748525)). Make sure to buy the 4th Edition.
* **You should prepare for the first day of class by ...**
    * Reading the syllabus (see the ["syllabus" tab](http://derekogle.com/NCHighways/Syllabus-Current) at the top of the course website).
    * Reading Chapter 1 and Chapter 14 in the *College Rules* textbook. Note that I have put copies of these chapters on the class webpage ([see here](https://derekogle.com/NCHighways/modules/OwnHighway/)). Use "Highways" (without quotes) to open the PDF after clicking on the link. I will not put other chapters for later modules on the webpage, so please plan to buy the book.

I look forward to working with you in this course this semester. Please let me know (dogle@northland.edu) if you have any questions.
